### ISSUE TITLE
Cannot handle nouns without plural forms

### ISSUE THREAD

**Issue by VanderpoelLiam** [VanderpoelLiam/automating-anki#2]
Running with the word `Quatsch` causes the program to crash. 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "automating-anki/src/automating_anki/main.py", line 52, in cli
    main(args.word, driver)
  File "automating-anki/src/automating_anki/main.py", line 27, in main
    note.uploadNote()
  File "automating-anki/src/automating_anki/note.py", line 84, in uploadNote
    self._setFields()
  File "automating-anki/src/automating_anki/note.py", line 72, in _setFields
    self._setExtraInfo()
  File "automating-anki/src/automating_anki/note.py", line 58, in _setExtraInfo
    self.extraInfo = self.wikiParser.getWordForms() + self.wikiParser.getIpa()
  File "automating-anki/src/automating_anki/webscraping.py", line 68, in getWordForms
    plural = rawWordForms.split("} ")[1]
IndexError: list index out of range
```

Probably as there is no plural form `Quatsch, kein Plural` and we do not handle this case correctly unlike a word with a plural e.g. `Hund, Plural: Hun·de`

**Comment by VanderpoelLiam** [comment]
`Ausgabe` also causes this crash. 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "automating-anki/src/automating_anki/main.py", line 56, in cli
    main(paste(), driver)
  File "automating-anki/src/automating_anki/main.py", line 27, in main
    note.uploadNote()
  File "automating-anki/src/automating_anki/note.py", line 84, in uploadNote
    self._setFields()
  File "automating-anki/src/automating_anki/note.py", line 72, in _setFields
    self._setExtraInfo()
  File "automating-anki/src/automating_anki/note.py", line 58, in _setExtraInfo
    self.extraInfo = self.wikiParser.getWordForms() + self.wikiParser.getIpa()
  File "automating-anki/src/automating_anki/webscraping.py", line 68, in getWordForms
    plural = rawWordForms.split("} ")[1]
IndexError: list index out of range
```
